"""NVIDIA Multi-Agent Builder - Main package."""

__version__ = "0.1.0"
__author__ = "NVIDIA"
__license__ = "Apache-2.0"

from nvidia_multi_agent_builder.config import Settings, settings, configure_logging, get_logger
from nvidia_multi_agent_builder.core import (
    MultiAgentBuilderError,
    ConfigurationError,
    ProviderError,
    AgentError,
    TaskError,
    Event,
    EventBus,
    EventType,
    event_bus,
    create_event,
    publish_event,
    Sandbox,
    SandboxLimits,
    SandboxResult,
    create_sandbox,
)
from nvidia_multi_agent_builder.models import (
    CompletionRequest,
    CompletionResponse,
    Message,
    ModelInfo,
    ModelProvider,
    ProviderError as ModelProviderError,
    ProviderErrorType,
    NVIDIAProvider,
    OpenAICompatibleProvider,
    LocalProvider,
    ProviderRegistry,
    create_default_registry,
    provider_registry,
    ModelRoute,
    ModelRouter,
    ModelHealth,
    ModelHealthState,
    HealthTracker,
    health_tracker,
    ModelScore,
    ScoringEngine,
    scoring_engine,
)

__all__ = [
    "__version__",
    "__author__",
    "__license__",
    "Settings",
    "settings",
    "configure_logging",
    "get_logger",
    "MultiAgentBuilderError",
    "ConfigurationError",
    "ProviderError",
    "AgentError",
    "TaskError",
    "Event",
    "EventBus",
    "EventType",
    "event_bus",
    "create_event",
    "publish_event",
    "Sandbox",
    "SandboxLimits",
    "SandboxResult",
    "create_sandbox",
    # Models
    "CompletionRequest",
    "CompletionResponse",
    "Message",
    "ModelInfo",
    "ModelProvider",
    "ModelProviderError",
    "ProviderErrorType",
    "NVIDIAProvider",
    "OpenAICompatibleProvider",
    "LocalProvider",
    "ProviderRegistry",
    "create_default_registry",
    "provider_registry",
    "ModelRoute",
    "ModelRouter",
    "ModelHealth",
    "ModelHealthState",
    "HealthTracker",
    "health_tracker",
    "ModelScore",
    "ScoringEngine",
    "scoring_engine",
]